### ISSUE TITLE
ListVms can't filter on `failed` state

### ISSUE THREAD

**Issue by blackwood821** [joyent/sdc-vmapi#73]
This doesn't appear to be a bug since the documentation says the following for the `state` input description:

```
running, stopped, active or destroyed
```
However I think it would be convenient to be able to filter on any state. For example, instead of doing this:

```
urlencode() {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            *) printf '%%%02X' "'$c"
        esac
    done
}

sdc-vmapi "/vms?predicate=$(urlencode '{ "eq" : [ "state", "failed" ] }')" | json -H
```
You could simply do this without getting an error:

```
sdc-vmapi /vms?state=failed | json -H
{
  "code": "ValidationFailed",
  "message": "Invalid Parameters",
  "errors": [
    {
      "field": "state",
      "code": "Invalid",
      "message": "Must be one of: active, destroyed, running, stopped"
    }
  ]
}
```

**Comment by danmcd** [comment]
> This doesn't appear to be a bug since the documentation says the following for the state input description:

But the documentation you cite shows a way to do this (which you also cite).  Might be nice to have, but we've other fish to fry and only so many cooks.
